# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0bba2d9983f597976b17e115cdf249c140b55c0fa8b957a2098bac7b2a60c581ee15c4067759cef5a0f643fac4cc93ecd4f73b1bea1a1517401666ddac4deb62

test:
  secret_key_base: 4b3c1d766dbe39b7fee222c96bc1681cb4e4f58edf6fd328d3f9e16fe9f1a59a657cdedcd4a96a586f048e81869b3e77894f6f168ae697f802ff3e1f1c3d2deb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
